// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/MemphisMealKitLinkPage-LhU6mj/index.tsx": () => import("../components/mockups/templates/MemphisMealKitLinkPage-LhU6mj/index.tsx"),
  "./components/mockups/templates/WarmAPIContactPage-qao9Pa/App.tsx": () => import("../components/mockups/templates/WarmAPIContactPage-qao9Pa/App.tsx")
};
