import type { AIProvider, ChatMessage, GenerationOptions, GenerationResult } from "./types";

// Demo provider returns clearly labeled placeholder content when no real API keys are configured
export class DemoProvider implements AIProvider {
  name = "demo";

  isConfigured(): boolean {
    return true; // Demo is always available
  }

  listModels(): string[] {
    return ["demo-model"];
  }

  async testConnection(): Promise<{ success: boolean; message: string; latencyMs: number }> {
    return { success: true, message: "Demo mode active — no API key required.", latencyMs: 0 };
  }

  async generate(messages: ChatMessage[], _options?: GenerationOptions): Promise<GenerationResult> {
    const start = Date.now();
    const lastMessage = messages[messages.length - 1]?.content ?? "";

    // Produce labeled demo output based on context keywords
    let content = "";
    const lc = lastMessage.toLowerCase();

    if (lc.includes("research plan") || lc.includes("questions")) {
      content = this.demoResearchPlan();
    } else if (lc.includes("outline")) {
      content = this.demoOutline();
    } else if (lc.includes("draft") || lc.includes("write") || lc.includes("section")) {
      content = this.demoDraftSection();
    } else if (lc.includes("natural") || lc.includes("tone") || lc.includes("edit")) {
      content = this.demoEditedSection();
    } else if (lc.includes("quality") || lc.includes("evaluat")) {
      content = this.demoQualityReport();
    } else if (lc.includes("verify") || lc.includes("claim")) {
      content = this.demoClaimVerification();
    } else {
      content = `[DEMO OUTPUT — Configure an AI provider in Settings to generate real content]\n\nThis is placeholder content generated by the demo provider. Add an OpenAI or Anthropic API key in Settings → AI Providers to enable real AI generation.`;
    }

    return {
      content,
      provider: "demo",
      model: "demo-model",
      inputTokens: 0,
      outputTokens: content.split(" ").length,
      latencyMs: Date.now() - start,
      estimatedCostUsd: 0,
    };
  }

  private demoResearchPlan(): string {
    return JSON.stringify({
      summary: "[DEMO] This research plan was generated by the demo provider. Configure a real AI provider to generate actual research plans.",
      timeframeStart: "2023-01-01",
      timeframeEnd: "2025-01-01",
      geographicBoundaries: "United States and Canada",
      sourceCategories: "Government publications, peer-reviewed journals, industry reports, news sources",
      potentialConflicts: "Some sources may have conflicting statistics; cross-reference with official sources",
      missingInformation: "Regional pricing data, recent policy changes",
      questions: [
        { question: "What are the primary factors affecting this topic?", priority: 1 },
        { question: "What does current research say about trends in this area?", priority: 2 },
        { question: "What are the most authoritative sources on this subject?", priority: 3 },
        { question: "Are there any notable recent changes or developments?", priority: 4 },
        { question: "What practical guidance exists for the intended audience?", priority: 5 },
      ],
    }, null, 2);
  }

  private demoOutline(): string {
    return JSON.stringify({
      sections: [
        { title: "Introduction", purpose: "Establish context and reader expectations", targetWordCount: 300, sortOrder: 0 },
        { title: "Background and Context", purpose: "Provide foundational knowledge", targetWordCount: 500, sortOrder: 1 },
        { title: "Key Concepts", purpose: "Define and explain core ideas", targetWordCount: 600, sortOrder: 2 },
        { title: "Practical Application", purpose: "Show real-world examples and guidance", targetWordCount: 700, sortOrder: 3 },
        { title: "Common Questions and Concerns", purpose: "Address reader objections", targetWordCount: 400, sortOrder: 4 },
        { title: "Conclusion and Next Steps", purpose: "Summarize and drive action", targetWordCount: 300, sortOrder: 5 },
      ],
    }, null, 2);
  }

  private demoDraftSection(): string {
    return `[DEMO OUTPUT — Configure an AI provider in Settings → AI Providers for real content]

This section demonstrates where your drafted content will appear. The real AI provider will generate research-backed, naturally written content based on your approved outline, brand voice, and research sources.

The drafting process will:
- Draw from your approved sources and claims
- Follow your brand's voice and tone guidelines
- Match your specified reading level and audience
- Maintain consistency with previously approved sections

To enable real content generation, add an API key for OpenAI, Anthropic, Google Gemini, or any OpenAI-compatible provider in the Settings page.`;
  }

  private demoEditedSection(): string {
    return `[DEMO — Natural Tone Edit Preview]

This is where your naturally-edited content will appear after the AI reviews it for:
- Robotic or formulaic phrasing
- Repetitive sentence structures
- Generic hooks and transitions
- Unnecessary corporate filler
- Unsupported certainty

Configure a real AI provider to enable editing.`;
  }

  private demoQualityReport(): string {
    return JSON.stringify({
      accuracyScore: 75,
      citationScore: 70,
      sourceQualityScore: 80,
      coverageScore: 65,
      coherenceScore: 78,
      continuityScore: 72,
      naturalnessScore: 68,
      usefulnessScore: 74,
      audienceFitScore: 76,
      brandFitScore: 71,
      readabilityScore: 73,
      repetitionScore: 77,
      overallPass: false,
      isPublicationReady: false,
      summary: "[DEMO] Quality evaluation placeholder. Configure a real AI provider to run actual evaluations.",
      issues: [
        { category: "naturalness", severity: "warning", description: "Some sections use formulaic introductions", suggestedFix: "Rewrite opening sentences to be more specific" },
        { category: "citations", severity: "info", description: "Two claims lack direct source citations", suggestedFix: "Add inline citations for statistical claims" },
      ],
    }, null, 2);
  }

  private demoClaimVerification(): string {
    return JSON.stringify({
      verificationStatus: "weakly_supported",
      confidence: 0.6,
      notes: "[DEMO] Claim verification placeholder. Configure a real AI provider for actual fact-checking.",
    }, null, 2);
  }
}

export const demoProvider = new DemoProvider();
